### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by kornelski**

### CODE REVIEW

**Comment by kornelski** [comment]
@bcmyers Could you merge this and make a release?

**Comment by kpcyrd** [comment]
Also interested in this :eyes:

**Comment by 5225225** [comment]
By the way, before/if this get merged, the dependencies should get bumped again, `itoa` needs a bump to 1.0 at least.

**Comment by pinkforest** [comment]
Someone should fork this perhaps

**Comment by bcmyers** [comment]
Apologies for neglecting this for so long. I just did a bunch of maintenance on this crate, including bumping dependency versions and ripping out deprecated code. And I published `0.4.2` on crates.io.

**Pull request closed without merging**
